# https://docs.travis-ci.com/user/languages/python/

language: python
sudo: false

before_install:
  - export PATH=$PATH:$HOME/.local/bin
  - export TXAIO_VERSION=$(grep -E '^(__version__)' ./txaio/_version.py | cut -d ' ' -f3 | sed -e 's|[u"'\'']||g')
  - export TXAIO_VCS_REF=`git --git-dir="./.git" rev-list -n 1 v${TXAIO_VERSION} --abbrev-commit`
  - export BUILD_DATE=`date -u +"%Y-%m-%d"`

install:
  - pip install tox codecov

script:
  - tox -c tox.ini -e $TOX_ENV

after_success:
  # since we use --parallel-mode to coverage inside Tox we use
  # "coverage combine" so the filename is always ".coverage"
  - cd test && coverage combine && codecov

matrix:
  fast_finish: true

  # https://github.com/travis-ci/travis-ci/issues/4794#issuecomment-143758799
  include:
    - env: TOX_ENV=flake8

    - python: 3.5
      env:
      - TOX_ENV=py35-tw187

    - python: 3.5
      env:
      - TOX_ENV=py35-tw1910

    - python: 3.5
      env:
      - TOX_ENV=py35-twtrunk

    - python: 3.5
      env:
      - TOX_ENV=py35-asyncio

    - python: 3.7
      env:
      - TOX_ENV=py37-tw187

    - python: 3.7
      env:
      - TOX_ENV=py37-tw1910

    - python: 3.7
      env:
      - TOX_ENV=py37-twtrunk

    - python: 3.7
      env:
      - TOX_ENV=py37-asyncio

    - python: 3.8
      env:
      - TOX_ENV=py38-tw187

    - python: 3.8
      env:
      - TOX_ENV=py38-tw1910

    - python: 3.8
      env:
      - TOX_ENV=py38-twtrunk

    - python: 3.8
      env:
      - TOX_ENV=py38-asyncio

    - python: pypy3
      env:
      - TOX_ENV=pypy3-tw187

    - python: pypy3
      env:
      - TOX_ENV=pypy3-tw1910

    - python: pypy3
      env:
      - TOX_ENV=pypy3-twtrunk

    - python: pypy3
      env:
      - TOX_ENV=pypy3-asyncio
    # https://docs.travis-ci.com/user/build-stages/matrix-expansion/
    - stage: deploy
      python: "3.7"
      dist: xenial
      sudo: required
      if: repo = crossbario/txaio AND branch = master AND type != pull_request
      #on:
      #  repo: crossbario/txaio
      #  branch: master
      #  # tags: true
      skip_cleanup: true
      provider: script
      script: pwd && ls -la && sh .travis-deploy.sh

# CI notifications
notifications:
  # IRC: chat messages on #crossbar-ci @ freenode
  irc:
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always
    channels:
      - "irc.freenode.org#crossbar-ci"
    use_notice: false
    skip_join: false

  # Gitter: activity feed on https://gitter.im/crossbario/ci
  webhooks:
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always
    urls:
      # travis encrypt "https://webhooks.gitter.im/e/7ef..." --org --repo crossbario/txaio
      - secure: bLUKiR27KsxcAHfCYEP2ZOrk1haqdOAEg9eRqYKopB1k4l8F/EkCBpN+X5+O3AT+wjOyq2msY9dA9jrAyZ1B6J+Dc1WgTihLyB36AVsNQtP3PGEX0jubpxPMnITqorO7saLqdwyKBuF0+8IWqM2MvEaPYy/kHL/utVvKxJy7ljY=

  # Slack: post feed on https://crossbario.slack.com/messages/CAT527K8D
  # https://crossbario.slack.com/services/
  slack:
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always
    rooms:
      # travis encrypt "crossbario:FYg..." --org --repo crossbario/txaio
      - secure: dPV0Nr3OtWIw7Af3r0xG4vNTpvjj3I67Mca0knqrplZpSOiSmDKRh1bqcAui557SBYhBpKNkUDQGeRvluTuPHv3TesKZNJGOq0PvDbxRJvCrnwqhRq/JXOFGGs2mC4hGXJ8wS67jn8A38pZSf4MRTGr9fPQKQqpPqXnkw4eokPc=
